### ISSUE TITLE
[Fabric/1.20.1] Wrong placement and statistics of gilded enderite armor

### ISSUE THREAD

**Issue by Captn138** [MaroonShaded/GildedArmorFabric#3]
Hello, I have noticed that the gilded enderite chestplate and leggings were kinda broken.
The chestplate appears with the expected stats of the helmet and goes into the helmet slot.
The Leggings appear with the expected stats of the chestplate and go into the chestplate slot.
Picture below should help understand it.
![image](https://github.com/MaroonShaded/GildedArmor/assets/25801033/a42a2611-b6fa-4772-8db8-57d6d4edf5af)

Nothing wrong with the boots and helmet thought:
![image](https://github.com/MaroonShaded/GildedArmor/assets/25801033/1e450b3b-8395-40f5-9bff-e9ef55906a88)

**Comment by MaroonShaded** [comment]
This is already fixed in the code, as you can see here 09428e2, and it was very funny when I noticed it.
I didn't realize I hadn't yet released the fix, I'll publish it this week. Thanks very much for pointing it out!

**Comment by Captn138** [comment]
Hey again, sorry to bother but is there any way to have the updated jar, even if you upload it to curseforge later?

**Comment by MaroonShaded** [comment]
The new version is now available on GitHub and Modrinth. I'm sorry I couldn't release it sooner.
